// action types

export const FETCH_BOOKS_API_CALL_REQUEST = 'FETCH_BOOKS_API_CALL_REQUEST'
export const FETCH_BOOKS_API_CALL_SUCCESS = 'FETCH_BOOKS_API_CALL_SUCCESS'
export const FETCH_BOOKS_API_CALL_FAILURE = 'FETCH_BOOKS_API_CALL_FAILURE'

export const ADD_BOOK_API_CALL_REQUEST = 'ADD_BOOK_API_CALL_REQUEST'
export const ADD_BOOK_API_CALL_SUCCESS = 'ADD_BOOK_API_CALL_SUCCESS'
export const ADD_BOOK_API_CALL_FAILURE = 'ADD_BOOK_API_CALL_FAILURE'

export const FETCH_BOOK_DETAIL_API_CALL_REQUEST = 'FETCH_BOOK_DETAIL_API_CALL_REQUEST'
export const FETCH_BOOK_DETAIL_API_CALL_SUCCESS = 'FETCH_BOOK_DETAIL_API_CALL_SUCCESS'
export const FETCH_BOOK_DETAIL_API_CALL_FAILURE = 'FETCH_BOOK_DETAIL_API_CALL_FAILURE'

export const HANDLE_USER_INPUT_CHANGE = 'HANDLE_USER_INPUT_CHANGE'

export const DELETE_BOOK_API_CALL_REQUEST = 'DELETE_BOOK_API_CALL_REQUEST'
export const DELETE_BOOK_API_CALL_SUCCESS = 'DELETE_BOOK_API_CALL_SUCCESS'
export const DELETE_BOOK_API_CALL_FAILURE = 'DELETE_BOOK_API_CALL_FAILURE'

export const SAVE_BOOK_DETAILS_API_CALL_REQUEST = 'SAVE_BOOK_DETAILS_API_CALL_REQUEST'
export const SAVE_BOOK_DETAILS_API_CALL_SUCCESS = 'SAVE_BOOK_DETAILS_API_CALL_SUCCESS'
export const SAVE_BOOK_DETAILS_API_CALL_FAILURE = 'SAVE_BOOK_DETAILS_API_CALL_FAILURE'

export const CLEAR_ADD_BOOKS = 'CLEAR_ADD_BOOKS'

export const CLEAR_BOOKS = 'CLEAR_BOOKS'

export const CLEAR_SAVE_BOOK_RESPONSE = 'CLEAR_SAVE_BOOK_RESPONSE'